## Convert between rotation formalisms

### quaternion_to_rotation_matrix()

In [1]:
from nimbro_utils.lazy import quaternion_to_rotation_matrix
rm = quaternion_to_rotation_matrix([0, 0.5, 0.2, 0.3])
print(rm)

[[-0.52631579 -0.31578947  0.78947368]
 [ 0.31578947  0.78947368  0.52631579]
 [-0.78947368  0.52631579 -0.31578947]]


### quaternion_to_yaw_pitch_roll()

In [2]:
from nimbro_utils.lazy import quaternion_to_yaw_pitch_roll
ypr = quaternion_to_yaw_pitch_roll([0, 0, 0, 1])
print(ypr)

[0. 0. 0.]


### yaw_pitch_roll_to_rotation_matrix()

In [3]:
from nimbro_utils.lazy import yaw_pitch_roll_to_rotation_matrix
rm = yaw_pitch_roll_to_rotation_matrix(ypr)
print(rm)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### yaw_pitch_roll_to_quaternion()

In [4]:
from nimbro_utils.lazy import yaw_pitch_roll_to_quaternion
quat = yaw_pitch_roll_to_quaternion(ypr)
print(quat)

[0. 0. 0. 1.]


### rotation_matrix_to_quaternion()

In [5]:
from nimbro_utils.lazy import rotation_matrix_to_quaternion
quat = rotation_matrix_to_quaternion(rm)
print(quat)

[0. 0. 0. 1.]


## Convert between NumPy and ROS2 messages

### create_point()

In [6]:
import time
from nimbro_utils.lazy import create_point
point_msg = create_point([0, 1, 2])
print(point_msg)
point_stamped_msg = create_point(point_msg, frame="base", stamp=time.time())
print(point_stamped_msg)

geometry_msgs.msg.Point(x=0.0, y=1.0, z=2.0)
geometry_msgs.msg.PointStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=407506704), frame_id='base'), point=geometry_msgs.msg.Point(x=0.0, y=1.0, z=2.0))


### create_vector()

In [7]:
import time
from nimbro_utils.lazy import create_vector
vector_msg = create_vector([0, 1, 2])
print(vector_msg)
vector_stamped_msg = create_vector(vector_msg, frame="base", stamp=time.time())
print(vector_stamped_msg)

geometry_msgs.msg.Vector3(x=0.0, y=1.0, z=2.0)
geometry_msgs.msg.Vector3Stamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=423227071), frame_id='base'), vector=geometry_msgs.msg.Vector3(x=0.0, y=1.0, z=2.0))


### create_quaternion()

In [8]:
import time
from nimbro_utils.lazy import create_quaternion
quaternion_msg = create_quaternion([0, 0, 0, 1])
print(quaternion_msg)
quaternion_stamped_msg = create_quaternion(quaternion_msg, frame="base", stamp=time.time())
print(quaternion_stamped_msg)

geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0)
geometry_msgs.msg.QuaternionStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=432755231), frame_id='base'), quaternion=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0))


### create_pose()

In [9]:
import time
from nimbro_utils.lazy import create_pose
pose_msg = create_pose(point=[1, 2, 3], quaternion=[0, 0, 0, 1])
print(pose_msg)
pose_stamped_msg = create_pose(pose_msg.position, pose_msg.orientation, frame="base", stamp=time.time())
print(pose_stamped_msg)

geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=1.0, y=2.0, z=3.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0))
geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=444828748), frame_id='base'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=1.0, y=2.0, z=3.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0)))


### create_transform()

In [10]:
import time
from nimbro_utils.lazy import create_transform

transform_msg = create_transform(vector=[1, 2, 3], quaternion=[0, 0, 0, 1])
print(transform_msg)

transform_stamped_msg = create_transform(transform_msg.translation, transform_msg.rotation, frame="base", stamp=time.time())
print(transform_stamped_msg)

geometry_msgs.msg.Transform(translation=geometry_msgs.msg.Vector3(x=1.0, y=2.0, z=3.0), rotation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0))
geometry_msgs.msg.TransformStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=457943439), frame_id='base'), child_frame_id='', transform=geometry_msgs.msg.Transform(translation=geometry_msgs.msg.Vector3(x=1.0, y=2.0, z=3.0), rotation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0)))


### create_pointcloud()

In [11]:
from nimbro_utils.lazy import create_pointcloud
pointcloud_stamped_msg = create_pointcloud([[0, 1, 2], [3, 4, 5]], frame="base", stamp=time.time())
print(pointcloud_stamped_msg)

sensor_msgs.msg.PointCloud2(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=468862295), frame_id='base'), height=1, width=2, fields=[sensor_msgs.msg.PointField(name='x', offset=0, datatype=7, count=1), sensor_msgs.msg.PointField(name='y', offset=4, datatype=7, count=1), sensor_msgs.msg.PointField(name='z', offset=8, datatype=7, count=1)], is_bigendian=False, point_step=12, row_step=24, data=[0, 0, 0, 0, 0, 0, 128, 63, 0, 0, 0, 64, 0, 0, 64, 64, 0, 0, 128, 64, 0, 0, 160, 64], is_dense=False)


### convert_transform()

In [12]:
from nimbro_utils.lazy import convert_transform, create_transform
transform_stamped_msg = create_transform(vector=[1, 2, 3], quaternion=[0, 0, 0, 1], frame="base", stamp=time.time())
converted_transform = convert_transform(transform_stamped_msg, target_format="PoseStamped")
print(converted_transform)

geometry_msgs.msg.PoseStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=483826398), frame_id='base'), pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=1.0, y=2.0, z=3.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0)))


### convert_point_and_vector()

In [13]:
from nimbro_utils.lazy import convert_point_and_vector, create_point
point_msg = create_point([0, 1, 2])
print(point_msg)
vector_msg = convert_point_and_vector(point_msg)
print(vector_msg)
point_msg_2 = convert_point_and_vector(vector_msg)
print(point_msg_2)

geometry_msgs.msg.Point(x=0.0, y=1.0, z=2.0)
geometry_msgs.msg.Vector3(x=0.0, y=1.0, z=2.0)
geometry_msgs.msg.Point(x=0.0, y=1.0, z=2.0)


### convert_pose_and_transform()

In [14]:
from nimbro_utils.lazy import convert_pose_and_transform
pose_msg = create_pose(point=[0, 1, 2], quaternion=[0, 0, 0, 1])
print(pose_msg)
transform_msg = convert_pose_and_transform(pose_msg)
print(transform_msg)
pose_msg_2 = convert_pose_and_transform(transform_msg)
print(pose_msg_2)

geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=0.0, y=1.0, z=2.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0))
geometry_msgs.msg.Transform(translation=geometry_msgs.msg.Vector3(x=0.0, y=1.0, z=2.0), rotation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0))
geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=0.0, y=1.0, z=2.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0))


### laserscan_to_pointcloud()

In [15]:
from sensor_msgs.msg import LaserScan
from nimbro_utils.lazy import laserscan_to_pointcloud
laserscan = LaserScan()
print(laserscan)
pointcloud = laserscan_to_pointcloud(laserscan)
print(pointcloud)

sensor_msgs.msg.LaserScan(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_id=''), angle_min=0.0, angle_max=0.0, angle_increment=0.0, time_increment=0.0, scan_time=0.0, range_min=0.0, range_max=0.0, ranges=[], intensities=[])
sensor_msgs.msg.PointCloud2(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_id=''), height=1, width=0, fields=[sensor_msgs.msg.PointField(name='x', offset=0, datatype=7, count=1), sensor_msgs.msg.PointField(name='y', offset=4, datatype=7, count=1), sensor_msgs.msg.PointField(name='z', offset=8, datatype=7, count=1)], is_bigendian=False, point_step=12, row_step=0, data=[], is_dense=False)


### message_to_numpy()

In [16]:
import time
from nimbro_utils.lazy import message_to_numpy, create_pose, create_pointcloud

pose_msg = create_pose(point=[1, 2, 3], quaternion=[0, 0, 0, 1])
print(pose_msg)
pose_np = message_to_numpy(pose_msg)
print(pose_np)

pointcloud_msg = create_pointcloud([[0, 1, 2], [3, 4, 5]], frame="base", stamp=time.time())
print(pointcloud_msg)
pointcloud_np = message_to_numpy(pointcloud_msg)
print(pointcloud_np)

geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=1.0, y=2.0, z=3.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0))
(array([1., 2., 3.], dtype=float32), array([0., 0., 0., 1.], dtype=float32))
sensor_msgs.msg.PointCloud2(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=541922569), frame_id='base'), height=1, width=2, fields=[sensor_msgs.msg.PointField(name='x', offset=0, datatype=7, count=1), sensor_msgs.msg.PointField(name='y', offset=4, datatype=7, count=1), sensor_msgs.msg.PointField(name='z', offset=8, datatype=7, count=1)], is_bigendian=False, point_step=12, row_step=24, data=[0, 0, 0, 0, 0, 0, 128, 63, 0, 0, 0, 64, 0, 0, 64, 64, 0, 0, 128, 64, 0, 0, 160, 64], is_dense=False)
[[0. 1. 2.]
 [3. 4. 5.]]


## Miscellaneous geometry utilities

### do_transform()

In [17]:
from nimbro_utils.lazy import do_transform, create_point, create_transform
point_msg = create_point([0, 1, 2])
print(point_msg)
transform_stamped_msg = create_transform(vector=[1, 1, 1], quaternion=[0, 0, 0, 1], frame="base", stamp=time.time())
print(transform_stamped_msg)
transformed_point_msg = do_transform(point_msg, transform_stamped_msg)
print(transformed_point_msg)

geometry_msgs.msg.Point(x=0.0, y=1.0, z=2.0)
geometry_msgs.msg.TransformStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=556707620), frame_id='base'), child_frame_id='', transform=geometry_msgs.msg.Transform(translation=geometry_msgs.msg.Vector3(x=1.0, y=1.0, z=1.0), rotation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0)))
geometry_msgs.msg.PointStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=1757517305, nanosec=556707620), frame_id='base'), point=geometry_msgs.msg.Point(x=1.0, y=2.0, z=3.0))


### rotate_pose()

In [18]:
from nimbro_utils.lazy import rotate_pose
pose_msg = create_pose(point=[1, 2, 3], quaternion=[0, 0, 0, 1])
print(pose_msg)
rotated_pose_msg = rotate_pose(pose_msg, delta=90, axis="z", degrees=True)
print(rotated_pose_msg)

geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=1.0, y=2.0, z=3.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0))
geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=1.0, y=2.0, z=3.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.7071067811865475, w=0.7071067811865476))


### rotation_from_vectors()

In [19]:
from nimbro_utils.lazy import rotation_from_vectors
quat = rotation_from_vectors([0, 0, 1], [1, 0, 0], rotation_format="quat")
print(quat)

[0.         0.70710678 0.         0.70710678]


### cosine_similarity()

In [20]:
from nimbro_utils.lazy import cosine_similarity
sim = cosine_similarity([1, 0, 0], [1, 1, 0])
print(sim)

0.7071067811865475


### quaternion_distance()

In [21]:
from nimbro_utils.lazy import quaternion_distance
print(quaternion_distance([0, 0.5, 0.2, 0.3], [0, 0.81110711, 0.32444284, 0.48666426], degrees=True))
print(quaternion_distance([0, 0.5, 0.2, 0.3], [0, 0, 0, 1], degrees=True))

0.0
90.0


### get_circle_pixels()

In [22]:
from nimbro_utils.lazy import get_circle_pixels
print(get_circle_pixels(center=[10, 10], radius=5, n=10, fill=False, image_shape=None))

[[ 5 10]
 [ 6  7]
 [ 6 13]
 [ 8  5]
 [ 8 15]
 [12  5]
 [12 15]
 [14  7]
 [14 13]
 [15 10]]


### get_iou()

In [23]:
from nimbro_utils.lazy import get_iou
iou = get_iou([0, 0, 5, 10], [5, 0, 10, 10])
print(iou)

0.09090909090909091


### convert_boxes()

In [24]:
from nimbro_utils.lazy import convert_boxes

In [25]:
boxes=[[1, 1, 5, 5]]
print(boxes)
converted_boxes = convert_boxes(boxes=boxes, source_format="xyxy_absolute", target_format="xywh_absolute")
print(converted_boxes)
converted_boxes = convert_boxes(boxes=boxes, source_format="xyxy_absolute", target_format="xywh_normalized", image_size=[10, 10])
print(converted_boxes)

[[1, 1, 5, 5]]
[[1, 1, 4, 4]]
[[0.1111111111111111, 0.1111111111111111, 0.4444444444444444, 0.4444444444444444]]
